- name: setup vprofile bastion instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
          - name: import VPC setup variable
            include_vars: ./bastion_setup

          - name: import VPC setup output
            include_vars: vars/output_vars

          - name: create a new ec2 key pair
            ec2_key:
               name: bastion_keypair
               region: us-east-1
            register: bastionkeyout

          - debug:
                var: bastionkeyout

          - name: store the key
            copy:
               content: "{{bastionkeyout.key.private_key}}"
               dest: ./bastionkeypair.pem
            when: bastionkeyout.changed == true
         
          - name: create SG for bastion host
            ec2_group:
                    name: bastion-host-SG
                    description: SG for bastion host
                    vpc_id: "{{vpcid}}"
                    region: "{{region}}"
                    rules:
                         - proto: tcp
                           from_port: 22
                           to_port: 22
                           cidr_ip: "{{MYIP}}"
            register: bastionSG_out                

          - name: creating ec2 instance
            ec2:
                    key_name: bastion_keypair
                    region: "{{region}}"
                    instance_type: t2.micro
                    image: "{{bastion_ami}}"
                    wait: yes
                    wait_timeout: 300
                    instance_tags:
                            Name: "Bastion_host"
                            Project: Vprofile
                            Owner: Devops Team
                    group_id: "{{bastionSG_out.group_id}}"
                    vpc_subnet_id: "{{pubsub1id}}"
                    exact_count: 1
                    count_tag:
                            Name: "Bastion_host"
                            Project: Vprofile
                            Owner: Devops Team
 
            register: BastionHost_out
                                  
          - name: insert bastionSG into vars/output_vars
            blockinfile:
                    path: vars/output_vars
                    backup: yes
                    block: |
                          bastionSG: {{bastionSG_out.group_id}}
                                        

