
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
       - name: create a new ec2 key pair
         ec2_key:
               name: my_keypair
               region: us-east-1
         register: keyout

       - debug:
                var: keyout

       - name: store the key 
         copy:
             content: "{{keyout.key.private_key}}"
             dest: ./mykeypair.pem
         when: keyout.changed == true


