
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
          - name: import var fies
            include_vars: ./vpc_setup

          - name: to create vpc
            ec2_vpc_net:
                           name: "{{VPC_name}}"
                           cidr_block: "{{vpcCider}}"
                           region: us-east-1
                           dns_support: yes
                           dns_hostnames: yes
                           tenancy: default
                           state: "{{state}}"
            register: vpcout

          - debug:
                    var: vpcout

          - name: create public subnet 1 in zone 1
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PubSub1Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone1}}"
                    map_public: yes
                    tags:
                            Name: PubSub1
            register: pubsub1_out

          - name: create public subnet 2 in zone 2
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PubSub2Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone2}}"
                    map_public: yes
                    tags:
                            Name: PubSub2
            register: pubsub2_out
 
          - name: create public subnet 3 in zone 3
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PubSub3Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone3}}"
                    map_public: yes
                    tags:
                            Name: PubSub3
            register: pubsub3_out

          - name: create private subnet 1 in zone 1
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PrivSub1Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone1}}"
                    map_public: yes
                    tags:
                            Name: PrivSub1
            register: privsub1_out

          - name: create private subnet 2 in zone 2
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PrivSub2Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone2}}"
                    map_public: yes
                    tags:
                            Name: PrivSub2
            register: privsub2_out

          - name: create private subnet 3 in zone 3
            ec2_vpc_subnet:
                    vpc_id: "{{vpcout.vpc.id}}"
                    cidr: "{{PrivSub3Cidr}}"
                    state: "{{state}}"
                    region: "{{region}}"
                    az: "{{zone3}}"
                    map_public: yes
                    tags:
                            Name: PrivSub3
            register: privsub3_out
          
          - name: creating internet gateway 
            ec2_vpc_igw:
                     vpc_id: "{{vpcout.vpc.id}}"
                     state: "{{state}}"
                     region: "{{region}}"
                     tags:
                             Name: vprofile_IGW
            register: igw_out

          - name: Set up public subnet route table
            ec2_vpc_route_table:
                   vpc_id: "{{vpcout.vpc.id}}"
                   region: "{{region}}"
                   tags:
                      Name: vprofile-PubRT
                   subnets:
                       - "{{pubsub1_out.subnet.id}}"
                       - "{{pubsub2_out.subnet.id}}"
                       - "{{pubsub3_out.subnet.id}}"
                   routes:
                      - dest: 0.0.0.0/0
                        gateway_id: "{{igw_out.gateway_id}}"
            register: PubRT_out
          
          - name: Create new nat gateway.
            ec2_vpc_nat_gateway:
                   state: "{{state}}"
                   subnet_id: "{{pubsub1_out.subnet.id}}"
                   wait: yes
                   region: "{{region}}"
                   if_exist_do_not_create: true
            register: nat_out  

          - name: Set up public subnet route table
            ec2_vpc_route_table:
                   vpc_id: "{{vpcout.vpc.id}}"
                   region: "{{region}}"
                   tags:
                      Name: vprofile-PrivRT
                   subnets:
                              - "{{privsub1_out.subnet.id }}"
                              - "{{privsub2_out.subnet.id }}"
                              - "{{privsub3_out.subnet.id }}"
                   routes:
                      - dest: 0.0.0.0/0
                        gateway_id: "{{nat_out.nat_gateway_id}}" 
            register: PrivRT_out
        
          - debug:
                  var: "{{item}}"
            loop:
                       - vpcout.vpc.id
                       - pubsub1_out.subnet.id
                       - pubsub2_out.subnet.id
                       - pubsub3_out.subnet.id
                       - igw_out.gateway_id
                       - privsub1_out.subnet.id
                       - privsub2_out.subnet.id
                       - privsub3_out.subnet.id
                       - igw_out.gateway_id
                       - PubRT_out.route_table.id
                       - nat_out.nat.gateway_id  
                       - PrivRT_out.route_table.id 

          - set_fact:
                     vpcid: "{{vpcout.vpc.id}}"
                     pubsub1id: "{{pubsub1_out.subnet.id}}"
                     pubsub2id: "{{pubsub2_out.subnet.id}}"
                     pubsub3id: "{{pubsub3_out.subnet.id}}"
                     privsub1id: "{{privsub1_out.subnet.id}}"
                     privsub2id: "{{privsub2_out.subnet.id}}"
                     privsub3id: "{{privsub3_out.subnet.id}}"
                     igwid: "{{igw_out.gateway_id}}"
                     pubRT: "{{PubRT_out.route_table.id}}"
                     privRT: "{{PrivRT_out.route_table.id}}"
                     cacheable: yes

          - name: Create variable filr for VPC output
            copy:
                   content: "vpcid: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1_out.subnet.id}}\npubsub2id: {{pubsub2_out.subnet.id}}\npubsub3id: {{pubsub3_out.subnet.id}}\nprivsub1id: {{privsub1_out.subnet.id}}\nprivsub2id: {{privsub2_out.subnet.id}}\nprivsub3id: {{privsub3_out.subnet.id}}\nigwid: {{igw_out.gateway_id}}\npubRT: {{PubRT_out.route_table.id}}\nprivRT: {{PrivRT_out.route_table.id}}"
                   dest: vars/output_vars
