- name: patching for the localhost
  hosts: localhost
  become: yes
  become_user: root
  tasks:
          - name: verifying is the app server is running or not
                    shell: if ps -ef | grep -i apache2 | grep -v grep > /dev/null ; then echo " process is running"; else echo " process not running";fi
            ignore_errors: yes
            register: app_out
          - debug: msg ="{{app_out.stdout}}"

          - name: decision piont to start patching 
            fail:
                    msg="{{ application is running hence stop execution further}}"

            when: app_out.stdout == "process is running"


